version: '2'
services:
  nano-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
  nano-redis:
    image: redis:3.2.6
    ports:
     - "6379:6379"
  nano-rest:
    build:
      context: ./restserver
      dockerfile: Dockerfile
    image: nano-rest
    ports:
     - "9001:9001"
    environment:
      NODE_ENV: develop
      REDIS_URL: redis://nano-redis:6379
      HUB_BUILD_VERSION: 2
  nano-relay:
    build:
      context: ./relayserver
      dockerfile: Dockerfile
    image: nano-relay
    ports:
     - "5000:5000"
    environment:
      NODE_ENV: develop
      REDIS_URL: redis://nano-redis:6379
      HUB_BUILD_VERSION: 2
  nano-webclient:
    build:
      context: ./webclient
      dockerfile: Dockerfile
    image: nano-webclient
    ports:
     - "5665:5665"
    environment:
      NODE_ENV: develop
      REDIS_URL: redis://nano-redis:6379
      HUB_BUILD_VERSION: 2

