version: '2'
services:
  nano-redis:
    image: redis:3.2.6
    ports:
     - "6379:6379"
  nano-rest:
    image: jakebladt/nanolnz-restserver
    ports:
     - "9001:9001"
    environment:
      NODE_ENV: develop
      REDIS_URL: redis://nano-redis:6379
      HUB_BUILD_VERSION: 2
  nano-relay:
    image: jakebladt/nanolnz-relay
    ports:
     - "5000:5000"
    environment:
      NODE_ENV: develop
      REDIS_URL: redis://nano-redis:6379
      HUB_BUILD_VERSION: 2
  nano-webclient:
    image: jakebladt/nanolnz-webclient
    ports:
     - "5665:5665"
    environment:
      NODE_ENV: develop
      REDIS_URL: redis://nano-redis:6379
      HUB_BUILD_VERSION: 2
