version: '2'
services:
  nano-redis:
    image: redis:3.2.6
    ports:
     - "6379:6379"
  nano-rest:
    build:
      context: ./restserver
      dockerfile: Dockerfile
    image: nano-rest
    ports:
     - "9001:9001"
    environment:
      NODE_ENV: develop
      REDIS_URL: redis://nano-redis:6379
  nano-relay:
    build:
      context: ./relayserver
      dockerfile: Dockerfile
    image: nano-relay
    ports:
     - "5000:5000"
    environment:
      NODE_ENV: develop
      REDIS_URL: redis://nano-redis:6379
